<?php
/**
 * Uninstall cleanup for Service Requests Form.
 *
 * Data is intentionally preserved by default. Cleanup runs only after an
 * administrator explicitly enables "Delete plugin data on uninstall" in the
 * plugin settings before uninstalling it.
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

if ( ! (bool) get_option( 'srf_quote_delete_data_on_uninstall', false ) ) {
	return;
}

/**
 * Normalize an attachment meta value to positive attachment IDs.
 *
 * @param mixed $value Stored post meta value.
 * @return int[]
 */
function srf_uninstall_attachment_ids( $value ) {
	if ( ! is_array( $value ) ) {
		$value = '' === $value || null === $value ? array() : array( $value );
	}

	$ids = array();
	foreach ( $value as $attachment_id ) {
		$attachment_id = absint( $attachment_id );
		if ( $attachment_id > 0 ) {
			$ids[] = $attachment_id;
		}
	}

	return array_values( array_unique( $ids ) );
}

/**
 * Permanently delete a WooCommerce product only when its ownership meta proves
 * that it was generated by this plugin for the expected record.
 *
 * @param int          $product_id Product post ID.
 * @param string       $meta_key   Ownership meta key.
 * @param string|int   $expected   Expected ownership value.
 * @return void
 */
function srf_uninstall_delete_owned_product( $product_id, $meta_key, $expected ) {
	$product_id = absint( $product_id );
	if ( ! $product_id || 'product' !== get_post_type( $product_id ) ) {
		return;
	}

	$actual = get_post_meta( $product_id, $meta_key, true );
	if ( (string) $actual !== (string) $expected ) {
		return;
	}

	wp_delete_post( $product_id, true );
}

/**
 * Delete all plugin request posts and their uploaded attachments.
 */
function srf_uninstall_delete_requests() {
	$request_ids = get_posts(
		array(
			'post_type'      => 'service_request',
			'post_status'    => 'any',
			'fields'         => 'ids',
			'posts_per_page' => -1,
			'no_found_rows'  => true,
		)
	);

	foreach ( $request_ids as $request_id ) {
		$file_ids = srf_uninstall_attachment_ids( get_post_meta( $request_id, '_sr_file_ids', true ) );
		foreach ( $file_ids as $attachment_id ) {
			wp_delete_attachment( $attachment_id, true );
		}
		delete_post_meta( $request_id, '_sr_remote_files' );
		wp_delete_post( $request_id, true );
	}

	$batch_ids = get_posts(
		array(
			'post_type'      => 'srf_upload_batch',
			'post_status'    => 'any',
			'fields'         => 'ids',
			'posts_per_page' => -1,
			'no_found_rows'  => true,
		)
	);

	foreach ( $batch_ids as $batch_id ) {
		wp_delete_post( $batch_id, true );
	}
}

/**
 * Delete plugin services and only the WooCommerce products generated for them.
 * Service gallery/featured media is deliberately retained because it may be
 * reused elsewhere in the Media Library.
 */
function srf_uninstall_delete_services() {
	$service_ids = get_posts(
		array(
			'post_type'      => 'sr_service',
			'post_status'    => 'any',
			'fields'         => 'ids',
			'posts_per_page' => -1,
			'no_found_rows'  => true,
		)
	);

	foreach ( $service_ids as $service_id ) {
		$product_id = absint( get_post_meta( $service_id, '_sr_wc_product_id', true ) );
		srf_uninstall_delete_owned_product( $product_id, '_sr_service_id', $service_id );
		wp_delete_post( $service_id, true );
	}
}

srf_uninstall_delete_requests();
srf_uninstall_delete_services();

// Delete the hidden custom-project carrier product only when ownership matches.
$project_product_id = absint( get_option( 'srf_project_quote_product_id', 0 ) );
srf_uninstall_delete_owned_product( $project_product_id, '_srf_project_quote_product', 'yes' );

global $wpdb;

// Remove custom quote data tables.
$quote_tables = array(
	$wpdb->prefix . 'srf_quote_materials',
	$wpdb->prefix . 'srf_quote_printers',
);
foreach ( $quote_tables as $table_name ) {
	// Table names are constructed exclusively from the trusted WordPress prefix.
	$wpdb->query( "DROP TABLE IF EXISTS `{$table_name}`" ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
}

// Remove plugin-owned user metadata for every account.
$user_meta_keys = array(
	'_srf_storage_used_bytes',
	'srf_used_bytes',
	'srf_quota_bytes',
	'seml_google_sub',
);
foreach ( $user_meta_keys as $meta_key ) {
	delete_metadata( 'user', 0, $meta_key, '', true );
}

// Clear any unfinished Google OAuth state transients.
$transient_like         = $wpdb->esc_like( '_transient_srf_google_state_' ) . '%';
$transient_timeout_like = $wpdb->esc_like( '_transient_timeout_srf_google_state_' ) . '%';
$wpdb->query(
	$wpdb->prepare(
		"DELETE FROM {$wpdb->options} WHERE option_name LIKE %s OR option_name LIKE %s",
		$transient_like,
		$transient_timeout_like
	)
); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching

$option_keys = array(
	// Legacy/basic settings.
	'srf_admin_email',
	'srf_allowed_file_types',
	'srf_max_file_size_mb',
	'srf_terms_url',
	'srf_request_form_url',

	// Quote and upload settings.
	'srf_quote_currency',
	'srf_quote_currency_symbol',
	'srf_quote_tax_rate',
	'srf_quote_service_fee',
	'srf_quote_setup_fee',
	'srf_quote_profit_margin',
	'srf_quote_max_upload_size',
	'srf_quote_allowed_extensions',
	'srf_quote_guest_ordering',
	'srf_quote_delete_data_on_uninstall',
	'srf_quote_notify_admin_email',

	// Workflow availability and project checkout.
	'srf_coming_soon_enabled',
	'srf_coming_soon_service_enabled',
	'srf_coming_soon_project_enabled',
	'srf_project_access_mode',
	'srf_project_checkout_enabled',
	'srf_frontend_language',
	'srf_admin_language',

	// Bambu starter profiles/resources.
	'srf_bambu_presets_enabled',
	'srf_bambu_hourly_cost',
	'srf_bambu_material_price_per_kg',
	'srf_bambu_presets_version',

	// WooCommerce mappings.
	'srf_service_form_page_id',
	'srf_service_after_submit',
	'srf_project_after_submit',
	'srf_service_product_category_id',
	'srf_project_quote_product_id',

	// Google sign-in settings.
	'srf_google_enabled',
	'srf_google_client_id',
	'srf_google_client_secret',
	'srf_google_redirect_uri',

	// Internal version markers.
	'srf_plugin_data_version',
	'srf_rewrite_version',
);

foreach ( $option_keys as $option_key ) {
	delete_option( $option_key );
}

remove_role( 'business_user' );
